project_id = "ebqrcizstqrifdxwnbcy"

[functions.detect-report-type]
verify_jwt = false

[functions.medical-chat]
verify_jwt = false

[functions.analyze-report]
verify_jwt = false

[functions.analyze-prescription]
verify_jwt = false

[functions.elevenlabs-tts]
verify_jwt = false

[functions.elevenlabs-stt-token]
verify_jwt = false

[functions.analyze-skin]
verify_jwt = false

[functions.predictive-health]
verify_jwt = false

[functions.symptom-checker]
verify_jwt = false

[functions.analyze-medicine]
verify_jwt = false

[functions.analyze-imaging]
verify_jwt = false

[functions.treatment-plan]
verify_jwt = false

[functions.ai-triage]
verify_jwt = false

[functions.analyze-ct]
verify_jwt = false

[functions.skin-progress]
verify_jwt = false

[functions.analyze-melanoma]
verify_jwt = false
