import { MedicalJSON, tryParseStructured } from './MedicalResponseRenderer';

export function exportMedicalPDF(content: string, timestamp?: string) {
  const data = tryParseStructured(content);
  if (!data) {
    // Fallback: export plain text
    exportPlainTextPDF(content, timestamp);
    return;
  }
  exportStructuredPDF(data, timestamp);
}

function exportStructuredPDF(data: MedicalJSON, timestamp?: string) {
  const dateStr = timestamp ? new Date(timestamp).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit'
  }) : new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit'
  });

  const riskColors: Record<string, string> = {
    low: '#22c55e', moderate: '#f59e0b', high: '#ef4444', critical: '#dc2626',
  };
  const riskColor = riskColors[data.risk_level] || '#f59e0b';

  const conditionsHTML = data.conditions?.map(c => {
    const probColors: Record<string, string> = { high: '#ef4444', medium: '#f59e0b', low: '#22c55e' };
    return `<span style="display:inline-block;padding:4px 12px;border-radius:8px;border:1px solid ${probColors[c.probability] || '#666'};color:${probColors[c.probability] || '#666'};font-size:12px;margin:2px 4px 2px 0;">${c.emoji || ''} ${c.name}</span>`;
  }).join('') || '';

  const symptomsHTML = data.symptoms_detected?.map(s =>
    `<span style="display:inline-block;padding:3px 10px;background:#f1f5f9;border-radius:6px;font-size:12px;margin:2px 4px 2px 0;">${s}</span>`
  ).join('') || '';

  const testsHTML = data.suggested_tests?.map(t =>
    `<li style="font-size:13px;padding:2px 0;">${t}</li>`
  ).join('') || '';

  const recsHTML = data.recommendations?.map(r =>
    `<li style="font-size:13px;padding:2px 0;">✓ ${r}</li>`
  ).join('') || '';

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Bee.dr AI Medical Report</title>
<style>
  @media print { body { margin: 0; } }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 700px; margin: 0 auto; padding: 40px 30px; color: #1a1a2e; }
  .header { border-bottom: 3px solid #6366f1; padding-bottom: 16px; margin-bottom: 24px; }
  .logo { font-size: 24px; font-weight: 800; color: #6366f1; }
  .date { font-size: 12px; color: #666; margin-top: 4px; }
  .badge { display: inline-block; padding: 4px 14px; border-radius: 20px; font-size: 12px; font-weight: 600; }
  .section { margin: 20px 0; }
  .section-title { font-size: 14px; font-weight: 700; color: #374151; margin-bottom: 8px; border-bottom: 1px solid #e5e7eb; padding-bottom: 4px; }
  .summary { font-size: 15px; line-height: 1.6; color: #374151; background: #f8fafc; padding: 16px; border-radius: 12px; border-left: 4px solid #6366f1; }
  .detailed { font-size: 13px; line-height: 1.7; color: #4b5563; white-space: pre-wrap; }
  .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; text-align: center; }
  ul { list-style: none; padding-left: 8px; }
</style></head><body>
<div class="header">
  <div class="logo">🐝 Bee.dr AI</div>
  <div class="date">Medical Report — ${dateStr}</div>
</div>

<div class="summary">${data.summary}</div>

<div style="margin:16px 0;">
  <span class="badge" style="background:${riskColor}22;color:${riskColor};border:1px solid ${riskColor}44;">
    Risk: ${data.risk_level.charAt(0).toUpperCase() + data.risk_level.slice(1)}
  </span>
  ${data.confidence != null ? `<span class="badge" style="background:#6366f122;color:#6366f1;border:1px solid #6366f144;margin-left:8px;">Confidence: ${data.confidence}%</span>` : ''}
</div>

${symptomsHTML ? `<div class="section"><div class="section-title">🔍 Symptoms Detected</div>${symptomsHTML}</div>` : ''}
${conditionsHTML ? `<div class="section"><div class="section-title">🧠 Possible Conditions</div>${conditionsHTML}</div>` : ''}
${data.specialist ? `<div class="section"><div class="section-title">👨‍⚕️ Recommended Specialist</div><p style="font-size:14px;">${data.specialist}</p></div>` : ''}
${testsHTML ? `<div class="section"><div class="section-title">🧪 Suggested Tests</div><ul>${testsHTML}</ul></div>` : ''}
${recsHTML ? `<div class="section"><div class="section-title">💡 Recommendations</div><ul>${recsHTML}</ul></div>` : ''}
${data.detailed_analysis ? `<div class="section"><div class="section-title">📋 Detailed Analysis</div><div class="detailed">${data.detailed_analysis}</div></div>` : ''}

<div class="footer">
  ${data.disclaimer || 'This report is AI-generated and for informational purposes only. Always consult a healthcare professional.'}
  <br>Generated by Bee.dr AI — ${dateStr}
</div>
</body></html>`;

  const printWindow = window.open('', '_blank');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    setTimeout(() => printWindow.print(), 500);
  }
}

function exportPlainTextPDF(content: string, timestamp?: string) {
  const dateStr = timestamp ? new Date(timestamp).toLocaleDateString() : new Date().toLocaleDateString();
  const html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>Bee.dr Chat Export</title>
<style>body{font-family:sans-serif;max-width:700px;margin:0 auto;padding:40px;color:#1a1a2e;} .header{font-size:24px;font-weight:800;color:#6366f1;border-bottom:3px solid #6366f1;padding-bottom:12px;margin-bottom:20px;} .content{font-size:14px;line-height:1.7;white-space:pre-wrap;} .footer{margin-top:30px;font-size:11px;color:#9ca3af;text-align:center;border-top:1px solid #e5e7eb;padding-top:12px;}</style></head>
<body><div class="header">🐝 Bee.dr AI — ${dateStr}</div><div class="content">${content.replace(/</g, '&lt;').replace(/>/g, '&gt;')}</div>
<div class="footer">Generated by Bee.dr AI. For informational purposes only.</div></body></html>`;
  const w = window.open('', '_blank');
  if (w) { w.document.write(html); w.document.close(); setTimeout(() => w.print(), 500); }
}
