import { useState, useEffect } from 'react';
import { motion } from 'framer-motion';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '@/contexts/AuthContext';
import { supabase } from '@/integrations/supabase/client';
import { Button } from '@/components/ui/button';
import { ArrowLeft, AlertTriangle, Heart, Droplets, Pill, Phone, Share2, User } from 'lucide-react';
import BottomNav from '@/components/BottomNav';
import { toast } from 'sonner';

const EmergencyCardPage = () => {
  const { user } = useAuth();
  const navigate = useNavigate();
  const [profile, setProfile] = useState<any>(null);
  const [healthProfile, setHealthProfile] = useState<any>(null);
  const [meds, setMeds] = useState<any[]>([]);
  const [emergencyContact, setEmergencyContact] = useState('');
  const [showCard, setShowCard] = useState(true);

  useEffect(() => {
    if (!user) return;
    Promise.all([
      supabase.from('profiles').select('*').eq('user_id', user.id).maybeSingle(),
      supabase.from('health_profiles').select('*').eq('user_id', user.id).maybeSingle(),
      supabase.from('medications').select('*').eq('user_id', user.id).eq('is_active', true),
    ]).then(([p, h, m]) => {
      setProfile(p.data);
      setHealthProfile(h.data);
      setMeds(m.data || []);
    });
  }, [user]);

  const shareCard = async () => {
    const cardText = `🚨 EMERGENCY HEALTH CARD
Name: ${profile?.display_name || 'N/A'}
Blood Group: ${healthProfile?.blood_group || 'N/A'}
Allergies: ${healthProfile?.allergies?.join(', ') || 'None'}
Conditions: ${healthProfile?.chronic_conditions?.join(', ') || 'None'}
Medications: ${meds.map(m => `${m.name} ${m.dosage || ''}`).join(', ') || 'None'}
Emergency Contact: ${emergencyContact || 'Not set'}
Generated by Bee.dr`;

    if (navigator.share) {
      await navigator.share({ title: 'Emergency Health Card', text: cardText });
    } else {
      await navigator.clipboard.writeText(cardText);
      toast.success('Card copied to clipboard');
    }
  };

  return (
    <div className="min-h-screen bg-background pb-20">
      <header className="border-b border-border bg-card sticky top-0 z-40">
        <div className="container mx-auto px-4 py-3 flex items-center gap-3">
          <Button variant="ghost" size="icon" onClick={() => navigate(-1)}><ArrowLeft className="w-4 h-4" /></Button>
          <AlertTriangle className="w-4 h-4 text-destructive" />
          <span className="text-sm font-display font-bold text-foreground">Emergency Health Card</span>
        </div>
      </header>

      <main className="container mx-auto px-4 py-6 max-w-lg">
        <motion.div initial={{ opacity: 0, y: 15 }} animate={{ opacity: 1, y: 0 }}
          className="bg-gradient-to-br from-destructive/5 to-warning/5 border-2 border-destructive/20 rounded-2xl p-6 space-y-4">
          {/* Header */}
          <div className="text-center">
            <div className="w-14 h-14 rounded-full bg-destructive/10 flex items-center justify-center mx-auto mb-2">
              <AlertTriangle className="w-7 h-7 text-destructive" />
            </div>
            <h2 className="text-lg font-display font-bold text-foreground">Emergency Health Card</h2>
            <p className="text-xs text-muted-foreground">Quick access health info for emergencies</p>
          </div>

          {/* Patient Info */}
          <div className="bg-card rounded-xl p-4 space-y-3">
            <div className="flex items-center gap-2">
              <User className="w-4 h-4 text-primary" />
              <span className="text-sm font-semibold text-foreground">{profile?.display_name || 'Name not set'}</span>
            </div>

            <div className="grid grid-cols-2 gap-3">
              <div className="flex items-center gap-2">
                <Droplets className="w-3.5 h-3.5 text-destructive" />
                <div>
                  <p className="text-[10px] text-muted-foreground uppercase">Blood Group</p>
                  <p className="text-sm font-bold text-foreground">{healthProfile?.blood_group || '—'}</p>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <Heart className="w-3.5 h-3.5 text-destructive" />
                <div>
                  <p className="text-[10px] text-muted-foreground uppercase">BMI</p>
                  <p className="text-sm font-bold text-foreground">
                    {healthProfile?.height_cm && healthProfile?.weight_kg
                      ? (healthProfile.weight_kg / Math.pow(healthProfile.height_cm / 100, 2)).toFixed(1)
                      : '—'}
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Allergies */}
          <div className="bg-card rounded-xl p-4">
            <p className="text-xs font-semibold text-destructive uppercase mb-2">⚠️ Allergies</p>
            {healthProfile?.allergies?.length > 0 ? (
              <div className="flex flex-wrap gap-1.5">
                {healthProfile.allergies.map((a: string) => (
                  <span key={a} className="text-xs px-2 py-1 bg-destructive/10 text-destructive rounded-full">{a}</span>
                ))}
              </div>
            ) : <p className="text-xs text-muted-foreground">No known allergies</p>}
          </div>

          {/* Chronic Conditions */}
          <div className="bg-card rounded-xl p-4">
            <p className="text-xs font-semibold text-warning uppercase mb-2">🏥 Chronic Conditions</p>
            {healthProfile?.chronic_conditions?.length > 0 ? (
              <div className="flex flex-wrap gap-1.5">
                {healthProfile.chronic_conditions.map((c: string) => (
                  <span key={c} className="text-xs px-2 py-1 bg-warning/10 text-warning rounded-full">{c}</span>
                ))}
              </div>
            ) : <p className="text-xs text-muted-foreground">None reported</p>}
          </div>

          {/* Active Medications */}
          <div className="bg-card rounded-xl p-4">
            <p className="text-xs font-semibold text-primary uppercase mb-2"><Pill className="w-3 h-3 inline mr-1" />Active Medications</p>
            {meds.length > 0 ? (
              <div className="space-y-1">
                {meds.map(m => (
                  <p key={m.id} className="text-xs text-foreground">{m.name} {m.dosage && `— ${m.dosage}`}</p>
                ))}
              </div>
            ) : <p className="text-xs text-muted-foreground">No active medications</p>}
          </div>

          {/* Emergency Contact */}
          <div className="bg-card rounded-xl p-4">
            <p className="text-xs font-semibold text-foreground uppercase mb-2"><Phone className="w-3 h-3 inline mr-1" />Emergency Contact</p>
            <input value={emergencyContact} onChange={e => setEmergencyContact(e.target.value)}
              placeholder="Enter emergency contact number"
              className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:ring-2 focus:ring-ring focus:outline-none" />
          </div>

          <Button onClick={shareCard} className="w-full gradient-primary text-primary-foreground" size="lg">
            <Share2 className="w-4 h-4 mr-2" /> Share Emergency Card
          </Button>
        </motion.div>
      </main>
      <BottomNav />
    </div>
  );
};

export default EmergencyCardPage;
